<?php
/**
 * @file
 * Uninstall function for the corporate blue front page slider module.
 */

/**
 * Implements hook_uninstall().
 */
function corporate_blue_front_page_slider_uninstall() {
  // Mainly for deleting front page slider title and body
  // (node default content for this content type).
  $node_type = 'front_page_slider';
  $nids = \Drupal::entityQuery('node')
    ->condition('type', $node_type, '=')
    ->execute();
  entity_delete_multiple('node', $nids);
}
